spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/logbook360_face
    username: postgres
    password: postgres
  jpa:
    show-sql: true

aws:
  region: ap-south-1
  s3:
    bucket-name: logbook360-face-dev
  rekognition:
    collection-prefix: logbook360-dev
    similarity-threshold: 75.0

face-recognition:
  liveness:
    enabled: false
